hydra:
    run:
        dir: "./runs/${env_id}__${experiment_name}__${seed}__${now:%Y-%m-%d_%H-%M-%S.%f}"
    job:
        chdir: false

experiment_name: "MixedExtrinsicCuriousBreakout"
env_id: "BreakoutNoFrameskip-v4"
seed: 1
use_cuda: true

save_model_frequency: 100000
total_timesteps: 5000000
learning_starts: 20000
update_frequency: 4
target_update_frequency: 8000
switch_head_frequency: 10000

batch_size: 64
learning_rate: 0.0003
memory_size: 100000
discount_factor: 0.99
target_smoothing_coefficient: 1.0
share_body: false

autotune_entropy: true
alpha: 0.2 # Redundant due to autotune_entropy=True
target_entropy_scale: 0.89

reward_sources:
  mixed:
    _target_: "rewards.MixedRewardGenerator.from_config"
    generators:
        extrinsic:
            _target_: "rewards.ExtrinsicRewardGenerator"
            _partial_: true
            reward_decay: 0.99
            use_dones: true
        curiosity:
            _target_: "rewards.CuriosityRewardGenerator"
            _partial_: true
            reward_decay: 0.99
            use_dones: false
            embedding_size: 128
            learning_rate: 0.0003
    weights:
        extrinsic: 1.0
        curiosity: 0.1
  
    
